# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'readygame.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow_ready(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(960, 540)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.playerLabel = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.playerLabel.setFont(font)
        self.playerLabel.setObjectName("playerLabel")
        self.horizontalLayout_2.addWidget(self.playerLabel)
        self.gridLayout.addLayout(self.horizontalLayout_2, 0, 0, 1, 1)
        self.readyButton = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(24)
        self.readyButton.setFont(font)
        self.readyButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.readyButton.setObjectName("readyButton")
        self.gridLayout.addWidget(self.readyButton, 0, 2, 1, 2)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.linkorButton = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setItalic(False)
        font.setStrikeOut(False)
        self.linkorButton.setFont(font)
        self.linkorButton.setObjectName("linkorButton")
        self.verticalLayout_2.addWidget(self.linkorButton)
        self.kreyserButton = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setItalic(False)
        self.kreyserButton.setFont(font)
        self.kreyserButton.setObjectName("kreyserButton")
        self.verticalLayout_2.addWidget(self.kreyserButton)
        self.esminecButton = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setItalic(False)
        self.esminecButton.setFont(font)
        self.esminecButton.setObjectName("esminecButton")
        self.verticalLayout_2.addWidget(self.esminecButton)
        self.torpedButton = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setItalic(False)
        font.setStrikeOut(False)
        self.torpedButton.setFont(font)
        self.torpedButton.setObjectName("torpedButton")
        self.verticalLayout_2.addWidget(self.torpedButton)
        self.gridLayout.addLayout(self.verticalLayout_2, 1, 3, 1, 1)
        self.boardMap = QtWidgets.QTableWidget(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.boardMap.setFont(font)
        self.boardMap.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.boardMap.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustIgnored)
        self.boardMap.setObjectName("boardMap")
        self.boardMap.setColumnCount(10)
        self.boardMap.setRowCount(10)
        item = QtWidgets.QTableWidgetItem()
        self.boardMap.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.boardMap.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.boardMap.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.boardMap.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.boardMap.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.boardMap.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.boardMap.setVerticalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.boardMap.setVerticalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.boardMap.setVerticalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.boardMap.setVerticalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.boardMap.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.boardMap.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.boardMap.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.boardMap.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.boardMap.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.boardMap.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.boardMap.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.boardMap.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.boardMap.setHorizontalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.boardMap.setHorizontalHeaderItem(9, item)
        self.gridLayout.addWidget(self.boardMap, 1, 0, 1, 1)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.linkorImage = QtWidgets.QLabel(self.centralwidget)
        self.linkorImage.setText("")
        self.linkorImage.setObjectName("linkorImage")
        self.verticalLayout.addWidget(self.linkorImage)
        self.kreyserImage = QtWidgets.QLabel(self.centralwidget)
        self.kreyserImage.setText("")
        self.kreyserImage.setObjectName("kreyserImage")
        self.verticalLayout.addWidget(self.kreyserImage)
        self.esminecImage = QtWidgets.QLabel(self.centralwidget)
        self.esminecImage.setText("")
        self.esminecImage.setObjectName("esminecImage")
        self.verticalLayout.addWidget(self.esminecImage)
        self.torpedImage = QtWidgets.QLabel(self.centralwidget)
        self.torpedImage.setText("")
        self.torpedImage.setObjectName("torpedImage")
        self.verticalLayout.addWidget(self.torpedImage)
        self.gridLayout.addLayout(self.verticalLayout, 1, 2, 1, 1)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.lcdNumber = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcdNumber.setProperty("intValue", 4)
        self.lcdNumber.setObjectName("lcdNumber")
        self.verticalLayout_3.addWidget(self.lcdNumber)
        self.lcdNumber_2 = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcdNumber_2.setProperty("intValue", 3)
        self.lcdNumber_2.setObjectName("lcdNumber_2")
        self.verticalLayout_3.addWidget(self.lcdNumber_2)
        self.lcdNumber_3 = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcdNumber_3.setProperty("intValue", 2)
        self.lcdNumber_3.setObjectName("lcdNumber_3")
        self.verticalLayout_3.addWidget(self.lcdNumber_3)
        self.lcdNumber_4 = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcdNumber_4.setProperty("intValue", 1)
        self.lcdNumber_4.setObjectName("lcdNumber_4")
        self.verticalLayout_3.addWidget(self.lcdNumber_4)
        self.gridLayout.addLayout(self.verticalLayout_3, 1, 1, 1, 1)
        self.label = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 960, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.playerLabel.setText(_translate("MainWindow", "PLAYER1"))
        self.readyButton.setText(_translate("MainWindow", "I am ready"))
        self.linkorButton.setText(_translate("MainWindow", "Choose where to put"))
        self.kreyserButton.setText(_translate("MainWindow", "Choose where to put"))
        self.esminecButton.setText(_translate("MainWindow", "Choose where to put"))
        self.torpedButton.setText(_translate("MainWindow", "Choose where to put"))
        item = self.boardMap.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "1"))
        item = self.boardMap.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "2"))
        item = self.boardMap.verticalHeaderItem(2)
        item.setText(_translate("MainWindow", "3"))
        item = self.boardMap.verticalHeaderItem(3)
        item.setText(_translate("MainWindow", "4"))
        item = self.boardMap.verticalHeaderItem(4)
        item.setText(_translate("MainWindow", "5"))
        item = self.boardMap.verticalHeaderItem(5)
        item.setText(_translate("MainWindow", "6"))
        item = self.boardMap.verticalHeaderItem(6)
        item.setText(_translate("MainWindow", "7"))
        item = self.boardMap.verticalHeaderItem(7)
        item.setText(_translate("MainWindow", "8"))
        item = self.boardMap.verticalHeaderItem(8)
        item.setText(_translate("MainWindow", "9"))
        item = self.boardMap.verticalHeaderItem(9)
        item.setText(_translate("MainWindow", "10"))
        item = self.boardMap.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "A"))
        item = self.boardMap.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "B"))
        item = self.boardMap.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "C"))
        item = self.boardMap.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "D"))
        item = self.boardMap.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "E"))
        item = self.boardMap.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "F"))
        item = self.boardMap.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "G"))
        item = self.boardMap.horizontalHeaderItem(7)
        item.setText(_translate("MainWindow", "H"))
        item = self.boardMap.horizontalHeaderItem(8)
        item.setText(_translate("MainWindow", "I"))
        item = self.boardMap.horizontalHeaderItem(9)
        item.setText(_translate("MainWindow", "J"))
        self.label.setText(_translate("MainWindow", "Number of cells."))
